from flask import Flask, render_template, request, jsonify
import pandas as pd
import json
import os
from datetime import datetime

app = Flask(__name__, 
            template_folder=os.path.dirname(os.path.abspath(__file__)),
            static_folder=os.path.dirname(os.path.abspath(__file__)),
            static_url_path='')

# Expanded cybersecurity news data with longer descriptions
news_data = [
    {"id": 1, "title": "Critical Vulnerability Found in Major SSL Library", "description": "Researchers discovered a critical flaw in OpenSSL that affects millions of websites worldwide. The bug allows attackers to intercept encrypted data and compromise privacy. This vulnerability has a CVSS score of 9.8 and affects OpenSSL versions prior to 3.0.7. Security teams are urged to update immediately as exploit code is already circulating. The vulnerability impacts both legacy systems and modern deployments, making it one of the most critical security issues of the year. Many organizations are working around the clock to patch their systems before malicious actors can exploit this weakness at scale.", "tags": ["Vulnerability", "SSL", "Encryption", "Critical"], "upvotes": 152, "downvotes": 11, "views": 450},
    {"id": 2, "title": "Quantum Encryption Breakthrough", "description": "Scientists unveiled a new quantum encryption model that could redefine data protection standards across the web. This breakthrough represents years of research in quantum cryptography and post-quantum computing security. The new algorithm is theoretically resistant to attacks from both classical and quantum computers. Researchers have already begun testing the implementation with major tech companies interested in integration. The practical applications could revolutionize how sensitive government and financial data is protected. Early testing shows the quantum encryption method maintains high performance while providing unprecedented security levels against future threats.", "tags": ["Quantum", "Encryption", "Research", "Innovation"], "upvotes": 122, "downvotes": 14, "views": 380},
    {"id": 3, "title": "Zero-Day Exploit in Windows Kernel", "description": "Microsoft patches critical zero-day vulnerability in Windows kernel that could allow remote code execution. The vulnerability was discovered by security researchers and disclosed responsibly to Microsoft before public release. Attackers could exploit this flaw to gain complete system control without user interaction. Microsoft released emergency patches for Windows 10, Windows 11, and Windows Server. System administrators are strongly recommended to apply patches immediately. The vulnerability affects millions of machines worldwide and could have severe consequences if left unpatched.", "tags": ["Windows", "Exploit", "Patch", "Critical"], "upvotes": 298, "downvotes": 8, "views": 720},
    {"id": 4, "title": "Ransomware Attack Hits Healthcare Sector", "description": "Major hospital network compromised by sophisticated ransomware attack. Patient data may be at risk including medical records, insurance information, and personal identifiers. The attack involved advanced persistent threat techniques and bypassed multiple security layers. Thousands of patient records were potentially exposed during the incident. The hospital paid a significant ransom but security experts remain concerned about data handling by cybercriminals. This incident highlights the critical need for robust backup systems and incident response planning in healthcare organizations. The attack was attributed to a known cybercriminal group with a history of targeting healthcare providers.", "tags": ["Ransomware", "Healthcare", "Data Breach", "Critical"], "upvotes": 187, "downvotes": 5, "views": 650},
    {"id": 5, "title": "New AI-Powered Phishing Detection Tool", "description": "Cybersecurity firm releases AI tool that can detect phishing emails with 98% accuracy. The tool uses machine learning models trained on millions of phishing and legitimate emails. It integrates seamlessly with existing email security infrastructure and requires minimal configuration. Organizations using the tool have reported significant reductions in successful phishing attacks. The AI system continuously learns from new phishing techniques and evolves its detection capabilities. Early adopters report 99.2% accuracy after fine-tuning for their specific environments. The tool also provides detailed analysis of why emails were flagged as suspicious.", "tags": ["AI", "Phishing", "Detection", "Machine Learning"], "upvotes": 245, "downvotes": 12, "views": 580},
    {"id": 6, "title": "DDoS Attack on Major ISP", "description": "Internet service provider experiences massive DDoS attack affecting millions of users worldwide. The attack used a combination of volumetric and application-layer assault techniques. Customers reported complete service outages lasting several hours during peak business times. The ISP's mitigation response demonstrated the need for better DDoS prevention infrastructure. Security experts believe the attack was conducted by a sophisticated threat actor testing new attack methodologies. Recovery efforts took significant time as attack patterns continued evolving throughout the incident. The incident prompted conversations about infrastructure resilience and emergency response protocols.", "tags": ["DDoS", "Infrastructure", "Attack", "Network"], "upvotes": 156, "downvotes": 9, "views": 420},
    {"id": 7, "title": "Blockchain Security Enhancement", "description": "New consensus mechanism improves blockchain security and reduces 51% attack risks. The enhancement introduces additional validation layers and cryptographic commitments. Testing shows the new mechanism can maintain throughput while dramatically improving security. The improvement addresses long-standing concerns about blockchain vulnerability to majority attacks. Implementation requires protocol upgrades that are backward compatible with existing infrastructure. Early blockchain networks adopting this mechanism report improved stakeholder confidence. Researchers believe this breakthrough opens new possibilities for permissionless distributed systems.", "tags": ["Blockchain", "Security", "Cryptocurrency", "Innovation"], "upvotes": 134, "downvotes": 18, "views": 390},
    {"id": 8, "title": "Cyber Espionage Campaign Uncovered", "description": "Security researchers discover sophisticated espionage campaign targeting government agencies. The campaign uses custom malware and advanced social engineering tactics. Multiple nation-state actors appear to be involved in coordinated intelligence gathering operations. Affected agencies have launched internal investigations and enhanced security protocols. The attack infrastructure reveals connections to known state-sponsored threat groups. Thousands of classified and sensitive documents were potentially accessed during the campaign. International incident response teams are collaborating to understand the full scope of the breach.", "tags": ["Espionage", "APT", "Government", "Advanced Threats"], "upvotes": 312, "downvotes": 7, "views": 890},
    {"id": 9, "title": "API Security Vulnerabilities Common in Web Apps", "description": "Study shows 60% of web applications have critical API security vulnerabilities. Researchers analyzed thousands of APIs across industries and found alarming security gaps. Common issues include authentication bypass, data exposure, and inadequate rate limiting. API security remains underfunded relative to its importance in modern application architectures. The study recommends comprehensive API security frameworks and regular security testing. Organizations are urged to audit their APIs immediately and implement security best practices. The findings highlight the need for API-first security strategies in development processes.", "tags": ["API", "Web Security", "Vulnerability", "Application"], "upvotes": 201, "downvotes": 11, "views": 510},
    {"id": 10, "title": "Password Manager Breach Incident", "description": "Popular password manager discovers security breach affecting user accounts. The breach compromised encrypted master passwords and user metadata. Investigators are still determining what information was accessed by unauthorized parties. Users are advised to change their master passwords and review account activity. The incident raises questions about password manager security practices and encryption implementations. The company released a detailed incident report explaining their response and remediation efforts. Cybersecurity experts discuss the implications for password management strategy adoption.", "tags": ["Password", "Breach", "Authentication", "Security"], "upvotes": 267, "downvotes": 6, "views": 780},
    {"id": 11, "title": "IoT Devices Show Major Security Gaps", "description": "Research reveals significant security vulnerabilities in popular IoT devices used in homes. Study finds widespread use of default credentials and outdated firmware in connected devices. Hackers can easily compromise these devices to launch attacks against home networks. The research identifies critical gaps in IoT manufacturer security practices and update mechanisms. Millions of homes potentially have vulnerable IoT devices on their networks. Security experts recommend network segmentation and device-specific access controls. The findings prompt manufacturers to announce enhanced security initiatives for future products.", "tags": ["IoT", "Vulnerability", "Smart Devices", "Home Security"], "upvotes": 189, "downvotes": 13, "views": 520},
    {"id": 12, "title": "Cloud Security Best Practices Updated", "description": "NIST releases updated guidelines for securing cloud infrastructure and services. The guidelines address emerging cloud security challenges including container security and serverless computing. New recommendations focus on identity and access management at scale. Organizations must implement the guidelines across multi-cloud and hybrid environments. The updated framework emphasizes security automation and continuous compliance monitoring. Cloud service providers are integrating the guidelines into their security offerings. The recommendations provide clear path forward for organizations modernizing their security posture.", "tags": ["Cloud", "Security", "Guidelines", "Best Practices"], "upvotes": 145, "downvotes": 10, "views": 380},
    {"id": 13, "title": "Malware Detection Using Machine Learning", "description": "New ML-based malware detection system shows 99% accuracy in identifying threats. The system analyzes behavioral patterns and code characteristics of suspicious files. Machine learning models trained on millions of known malware samples improve detection capabilities. Traditional signature-based approaches miss advanced malware that new system easily identifies. Organizations implementing the system report dramatic reduction in successful malware infections. The system integrates with existing security infrastructure and requires minimal operational changes. Researchers continue training models on emerging malware to maintain detection accuracy.", "tags": ["Malware", "Machine Learning", "Detection", "Threat Prevention"], "upvotes": 223, "downvotes": 9, "views": 640},
    {"id": 14, "title": "Supply Chain Attack on Software Company", "description": "Major software company becomes victim of supply chain attack compromising software distribution. Attackers inserted malicious code into legitimate software updates distributed to thousands of customers. The attack went undetected for weeks before security researchers discovered suspicious behavior. Affected organizations must audit systems and remove compromised software immediately. The incident demonstrates sophisticated adversary capabilities and supply chain vulnerabilities. Software vendors are implementing enhanced code review and signing procedures. The attack prompts industry conversation about reducing supply chain security risks.", "tags": ["Supply Chain", "Attack", "Software", "Distribution"], "upvotes": 278, "downvotes": 8, "views": 720},
    {"id": 15, "title": "Encryption Key Management Best Practices", "description": "Security experts discuss essential practices for managing encryption keys in enterprise environments. Proper key management is critical foundation for all cryptographic security implementations. Organizations must implement key rotation, access controls, and audit logging for all encryption keys. Cloud key management services provide scalable solutions for enterprises managing thousands of keys. The session covers regulatory requirements and compliance considerations for key management. Organizations lacking centralized key management face significant security and operational risks. Best practices emphasize separation of duties and automated key lifecycle management.", "tags": ["Encryption", "Key Management", "Enterprise", "Compliance"], "upvotes": 112, "downvotes": 7, "views": 320},
    {"id": 16, "title": "Insider Threat Detection Improved", "description": "New behavioral analysis tool helps detect insider threats with higher accuracy. The tool monitors user activity patterns and identifies anomalous behavior indicating potential threats. Advanced analytics combine multiple data sources to detect sophisticated insider attacks. User activity monitoring must balance security with privacy considerations and employee rights. Organizations implementing behavioral analytics report improved threat detection and faster response times. The tool learns normal behavior patterns and alerts security teams to significant deviations. Training data includes historical insider threat incidents from multiple organizations and industries.", "tags": ["Insider Threat", "Detection", "Behavior Analytics", "User Monitoring"], "upvotes": 198, "downvotes": 12, "views": 480},
    {"id": 17, "title": "Security Awareness Training Reduces Breaches", "description": "Study shows companies with comprehensive security training reduce breach incidents by 45%. Employee security awareness remains critical component of defense against social engineering attacks. Well-trained employees can identify phishing attempts and avoid security mistakes. Training programs should include regular updates and simulated attack scenarios. Organizations investing in security training report improved security culture throughout the company. The study found that consistent training reduces both successful attacks and security incidents. Security awareness training provides exceptional return on investment for organizations.", "tags": ["Training", "Awareness", "Prevention", "Human Security"], "upvotes": 167, "downvotes": 10, "views": 420},
    {"id": 18, "title": "Multi-Factor Authentication Adoption Growing", "description": "Industry report shows increasing adoption of multi-factor authentication across enterprises. MFA significantly reduces successful account compromise even when passwords are stolen. Organizations implementing MFA report dramatic reduction in unauthorized account access incidents. Cloud services and SaaS applications leading adoption of MFA as standard security feature. Hardware security keys provide strongest MFA protection against phishing attacks. Regulatory requirements increasingly mandate MFA for sensitive systems and data access. The trend toward MFA adoption represents major positive shift in overall security posture.", "tags": ["MFA", "Authentication", "Security", "Access Control"], "upvotes": 134, "downvotes": 8, "views": 360},
    {"id": 19, "title": "Biometric Security Breakthrough", "description": "New biometric authentication system combines fingerprint and facial recognition. Multi-modal biometric approach dramatically improves security compared to single modalities. Spoof attacks become significantly more difficult when bypassing multiple independent biometric factors. The system achieves 99.97% accuracy in authenticating authorized users while rejecting unauthorized attempts. Integration into smartphones and security systems provides convenient and secure authentication. Enterprises deploying biometric systems report improved user experience and security. Privacy advocates emphasize importance of secure storage and handling of biometric data.", "tags": ["Biometric", "Authentication", "Innovation", "Technology"], "upvotes": 245, "downvotes": 11, "views": 610},
    {"id": 20, "title": "Cyber Threat Intelligence Sharing", "description": "Government agencies launch platform to share real-time cyber threat intelligence. The platform enables organizations to receive alerts about emerging threats and attack indicators. Threat intelligence sharing accelerates collective defense against coordinated cyber operations. Private sector organizations can participate and contribute intelligence to community. The platform includes structured data formats facilitating automated threat detection systems. Participants report improved ability to detect and respond to threats affecting their networks. Threat intelligence sharing represents evolution toward collaborative cybersecurity approach.", "tags": ["Threat Intelligence", "Sharing", "Government", "Collaboration"], "upvotes": 176, "downvotes": 9, "views": 470},
    {"id": 21, "title": "Email Security Gateway Upgrade", "description": "Enterprise email security solution adds AI-powered threat detection capabilities. The upgrade provides advanced phishing detection and malware analysis at email gateway. AI systems identify sophisticated attacks that traditional signature-based systems miss. Organizations report significant reduction in successful phishing attacks reaching users. The system learns from security events and continuously improves threat detection accuracy. Integration with incident response systems enables automated threat containment. Email security remains critical component of comprehensive defense-in-depth security strategy.", "tags": ["Email", "Security", "AI", "Threat Detection"], "upvotes": 145, "downvotes": 10, "views": 350},
    {"id": 22, "title": "Web Application Firewall Enhancement", "description": "WAF technology improved to detect and block advanced application-layer attacks. Enhanced filtering identifies zero-day attacks and novel attack patterns in real time. Machine learning models analyze web traffic and identify suspicious patterns automatically. Organizations deploying advanced WAF report significant reduction in successful web application attacks. The enhancement addresses evolving threat landscape including API attacks and sophisticated exploits. WAF deployments provide critical protection for externally facing web applications and services. Continuous updates ensure WAF remains effective against emerging attack techniques.", "tags": ["WAF", "Firewall", "Application Security", "Protection"], "upvotes": 189, "downvotes": 7, "views": 440},
    {"id": 23, "title": "Incident Response Plan Best Practices", "description": "Security professionals share effective strategies for incident response planning and execution. Well-prepared incident response plans minimize damage and recovery time during security breaches. Organizations should establish clear roles, responsibilities, and communication procedures. Regular testing through incident response drills identifies gaps in plans and procedures. External incident responders can supplement internal teams during major incidents. Documented procedures and automation accelerate response to security incidents. Post-incident reviews provide valuable learning opportunities for continuous improvement.", "tags": ["Incident Response", "Planning", "Best Practices", "Emergency"], "upvotes": 156, "downvotes": 11, "views": 400},
    {"id": 24, "title": "Vulnerability Assessment Tools Compared", "description": "Comprehensive review of top vulnerability assessment and scanning tools available today. Different tools offer unique capabilities for identifying security weaknesses in systems and applications. Organizations should select tools matching their environment complexity and requirements. Regular vulnerability scanning identifies security issues before attackers can exploit them. Integration of vulnerability assessment with patch management improves remediation efficiency. Automated scanning reduces manual effort required for vulnerability identification and tracking. Most organizations use multiple tools to achieve comprehensive vulnerability coverage across their environment.", "tags": ["Vulnerability", "Assessment", "Tools", "Scanning"], "upvotes": 134, "downvotes": 13, "views": 380},
    {"id": 25, "title": "Penetration Testing Standards Released", "description": "Industry organization publishes updated standards for ethical penetration testing. The standards define methodologies, scope considerations, and professional conduct expectations. Penetration testers must follow strict guidelines to ensure safety and legality of testing activities. Organizations conducting penetration tests should verify tester credentials and adherence to standards. Regular penetration testing identifies vulnerabilities that automated tools might miss. Authorized penetration testing provides valuable insights for improving security posture. Standards help protect both testers and organizations involved in penetration testing activities.", "tags": ["Penetration Testing", "Standards", "Ethics", "Testing"], "upvotes": 201, "downvotes": 9, "views": 520},
    {"id": 26, "title": "Social Engineering Attacks Increase", "description": "Report shows 300% increase in sophisticated social engineering attacks targeting businesses. Attackers increasingly use social engineering as preferred initial attack vector. Human psychology remains weakest link in security chain despite technology improvements. Organizations must invest heavily in security awareness training and education programs. Social engineering attack success correlates with financial losses and data breaches. Implementing verification procedures and authentication reduces social engineering attack effectiveness. Security culture emphasizing skepticism and verification procedures provides important protection against social engineering.", "tags": ["Social Engineering", "Attack", "Threat", "Human Security"], "upvotes": 267, "downvotes": 8, "views": 680},
    {"id": 27, "title": "Secure Code Development Training", "description": "Online platform launches comprehensive courses for secure code development practices. Secure coding training enables developers to identify and prevent common security vulnerabilities. Organizations investing in developer security training see significant reduction in application security flaws. Training covers OWASP Top 10 vulnerabilities and best practices for secure implementation. Developers completing training produce more secure code with fewer security issues requiring remediation. Continuous learning through refresher courses keeps developers updated on emerging threats. Secure development training provides excellent return on investment through reduced security incidents.", "tags": ["Development", "Training", "Secure Code", "Best Practices"], "upvotes": 178, "downvotes": 10, "views": 410},
    {"id": 28, "title": "Mobile App Security Vulnerabilities", "description": "Security audit reveals critical vulnerabilities in popular mobile applications. Many mobile apps store sensitive data insecurely or transmit data without encryption. Mobile platform security features provide protection but applications must implement proper security practices. Users download millions of vulnerable applications potentially exposing personal and financial data. Mobile app developers should undergo security training and implement secure coding practices. Regular security testing of mobile applications identifies vulnerabilities before malicious exploitation. The popularity of mobile applications makes app security critically important for user protection.", "tags": ["Mobile", "App Security", "Vulnerability", "Privacy"], "upvotes": 223, "downvotes": 12, "views": 550},
    {"id": 29, "title": "Database Encryption Standards Updated", "description": "New standards for database encryption improve data protection in enterprise systems. Updated standards address both data at rest and data in motion protection requirements. Encryption key management receives increased emphasis in updated standards. Organizations must evaluate current encryption implementations against new standards. Database encryption remains important control for protecting sensitive data from unauthorized access. Cloud databases increasingly offer built-in encryption features simplifying compliance. Compliance with updated standards helps organizations meet regulatory and legal requirements.", "tags": ["Database", "Encryption", "Standards", "Data Protection"], "upvotes": 145, "downvotes": 9, "views": 370},
    {"id": 30, "title": "Bug Bounty Program Records", "description": "Tech companies pay record amounts for security researchers finding critical bugs. Bug bounty programs provide effective mechanism for identifying vulnerabilities in complex systems. Security researchers earning significant income through bug bounties incentivizes their participation. Companies benefit from external security expertise and comprehensive vulnerability identification. Bug bounty platforms facilitate connection between researchers and organizations seeking security improvements. Total bug bounty payments exceed billions of dollars annually across all programs. The trend toward increased bug bounty participation strengthens collective cybersecurity posture.", "tags": ["Bug Bounty", "Rewards", "Research", "Vulnerability"], "upvotes": 289, "downvotes": 10, "views": 720},
    {"id": 31, "title": "Zero Trust Architecture Implementation", "description": "Enterprise adopts zero trust security model improving network security posture. Zero trust architecture assumes no implicit trust requiring verification for all access requests. Implementation requires identity verification, access controls, and continuous monitoring throughout network. Organizations transitioning to zero trust report improved security and reduced breach impact. Zero trust principles apply across network, application, and data protection layers. The model provides framework for defending against both external and internal threats. Zero trust adoption represents fundamental shift toward more secure architecture principles.", "tags": ["Zero Trust", "Architecture", "Network", "Security Model"], "upvotes": 234, "downvotes": 11, "views": 580},
    {"id": 32, "title": "Cryptography Advancements in 2024", "description": "Latest developments in cryptographic algorithms and protocols for modern security. Researchers continue advancing cryptographic science addressing quantum computing challenges. Post-quantum cryptography research focuses on algorithms resistant to quantum attacks. Organizations must plan cryptographic upgrades as quantum computing technology matures. New cryptographic protocols improve efficiency and security compared to previous standards. Industry adoption of cryptographic advancements follows standardization and validation processes. Cryptography remains fundamental technology underlying all modern security infrastructure.", "tags": ["Cryptography", "Algorithm", "Innovation", "Post-Quantum"], "upvotes": 198, "downvotes": 14, "views": 480},
    {"id": 33, "title": "Red Team vs Blue Team Exercises", "description": "Organizations conduct comprehensive security exercises to test defensive capabilities. Red teams simulate attackers attempting to compromise systems and networks. Blue teams defend systems against red team attacks revealing defensive capabilities and weaknesses. These exercises provide valuable training and identify areas requiring security improvements. Organizations conducting regular red team exercises demonstrate significantly improved security incident response. Exercise results guide security investment decisions and training priorities. Red team exercises represent best practice for validating security measures and incident response procedures.", "tags": ["Red Team", "Blue Team", "Exercise", "Security Testing"], "upvotes": 167, "downvotes": 9, "views": 420},
    {"id": 34, "title": "Security Operations Center Modernization", "description": "SOCs upgrade to modern platforms for improved threat detection and response. Modernization includes enhanced analytics, automation, and integration capabilities. Updated SOCs reduce alert fatigue through improved alert quality and relevance. Automation of routine tasks frees SOC analysts to focus on complex investigations. Organizations reporting SOC modernization see improved mean time to detect threats. Advanced analytics correlate data from multiple sources providing comprehensive threat visibility. Modernized SOCs provide foundation for effective security incident response and prevention.", "tags": ["SOC", "Operations", "Modernization", "Automation"], "upvotes": 145, "downvotes": 8, "views": 380},
    {"id": 35, "title": "Compliance and Regulations Guide", "description": "Complete guide to GDPR, HIPAA, and other compliance requirements in cybersecurity. Regulatory landscape continues expanding with new requirements affecting organizations globally. Organizations must understand applicable regulations and implement required security controls. Compliance violations result in significant fines and reputational damage for organizations. Regular compliance audits verify implementation of required controls and identify gaps. Security teams must collaborate with legal and compliance teams on regulatory requirements. Proper compliance implementation demonstrates commitment to protecting sensitive data and user privacy.", "tags": ["Compliance", "Regulations", "GDPR", "HIPAA"], "upvotes": 212, "downvotes": 12, "views": 590},
]

# Initialize DataFrame
df = pd.DataFrame(news_data)

@app.route('/')
def index():
    return app.send_static_file('feed.html')

@app.route('/feed.html')
def feed():
    return app.send_static_file('feed.html')

@app.route('/api/feed', methods=['GET'])
def get_feed():
    search = request.args.get('search', '').lower()
    tag = request.args.get('tag', '').lower()
    trending = request.args.get('trending', 'false').lower() == 'true'

    filtered_df = df.copy()

    if search:
        filtered_df = filtered_df[
            filtered_df['title'].str.lower().str.contains(search) |
            filtered_df['description'].str.lower().str.contains(search)
        ]

    if tag:
        filtered_df = filtered_df[filtered_df['tags'].apply(lambda x: tag in [t.lower() for t in x])]

    if trending:
        filtered_df = filtered_df.nlargest(10, 'upvotes')

    return jsonify(filtered_df.to_dict('records'))

@app.route('/api/stats', methods=['GET'])
def get_stats():
    stats = {
        'total_posts': len(df),
        'total_upvotes': int(df['upvotes'].sum()),
        'total_views': int(df['views'].sum())
    }
    return jsonify(stats)

@app.route('/api/vote', methods=['POST'])
def vote():
    data = request.json
    post_id = data.get('id')
    vote_type = data.get('type')

    if post_id in df['id'].values:
        if vote_type == 'upvote':
            df.loc[df['id'] == post_id, 'upvotes'] += 1
        elif vote_type == 'downvote':
            df.loc[df['id'] == post_id, 'downvotes'] += 1
        return jsonify({'success': True})
    return jsonify({'success': False}), 404

@app.after_request
def add_header(response):
    response.cache_control.no_cache = True
    response.cache_control.no_store = True
    response.cache_control.must_revalidate = True
    response.cache_control.max_age = 0
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response

if __name__ == '__main__':
    app.run(debug=True, port=5000)
